### ISSUE TITLE
Add grid view option to `--layout`, implement grid view output

### ISSUE THREAD

**Issue by hedythedev** [hedythedev/starcli#23]
Currently, for the `--layout` option we have `list` or `table`, it would be awesome if we also have a `grid` option so the output can be displayed in grid view format. 

To do so we should add a function called something like `grid_layout()` in `starcli/layouts.py`, with one parameter `repos`. This function should then be imported from `starcli/__main__.py` using the same logic as `list_layout` and `table_layout` to be called when `--layout grid` is specified. Also, don't forget to update `click.Choices(["list", "table", "grid"])` in the `starcli/__main__.py`, with the help argument updated and the usage copied to the README.

You can use the [panel](https://rich.readthedocs.io/en/latest/panel.html) and [columns](https://rich.readthedocs.io/en/latest/columns.html) functionality from rich. See [this](https://github.com/willmcgugan/rich/blob/master/examples/columns.py) example for reference

Start a pull request when you are done (or have started the draft PR)

Edit: added columns link as to the suggestion from @willmcgugan

**Comment by willmcgugan** [comment]
You could render a grid view with the [Columns](https://rich.readthedocs.io/en/latest/columns.html) class. See columns.py in the examples directory.

**Comment by hedythedev** [comment]
Thank you for letting me know, I will have a look

**Comment by hedythedev** [comment]
This issue is now available for grabs, anyone can drop in and request to be assigned :D

**Comment by swellander** [comment]
Hi there! Is this no longer up for grabs?

**Comment by hedythedev** [comment]
Of course it’s available! Don’t worry about the label movements, I was just organising them and decided to just keep a good first issue label. Feel free to take this up if you like 😄

**Comment by hedythedev** [comment]
Just a reminder, I have done a quick clean up to the branches and the GitHub action files, so you might wanna pull these new changes to your fork as needed. And use the ‘main’ branch to start a pr

**Comment by swellander** [comment]
Ok, sounds good 👍 sorry for the delay. I'd love to take this one.

**Comment by hedythedev** [comment]
I think if the description can make a single box too big to fit then we could show parts of the description, like
```
Python composable command line
Interface toolkit for beginners to...
```
With the `...` When the description exceeds a max character constant.

However if you really think we should leave it out then it’s fine.

**Comment by swellander** [comment]
Got it, good call. I think the `...` will work well.

**Comment by hedythedev** [comment]
How’s the progress? Once you open a pr I’ll add you to all-contributors list

**Comment by swellander** [comment]
Just about done! Aiming to have the PR up later today.
