### ISSUE TITLE
Filtering by spoken language (new option)

### ISSUE THREAD

**Issue by hedythedev** [hedythedev/starcli#45]
Currently we can only filter by language, date, and stars, we should also add `--spoken-language` option to filter by spoken language (Chinese, English, etc):
![Screenshot_20200711_080341](https://user-images.githubusercontent.com/50042066/87211655-050c4180-c30a-11ea-9937-0d5a55151b81.jpg)

Github API can probably filter it for us, if not, we might have to scrape it from the website. 
Remember to update the readme when adding a new option

**Comment by Saif807380** [comment]
I would like to work on this.

**Comment by hedythedev** [comment]
Ok @Saif807380 👍🏼

**Comment by Saif807380** [comment]
@hedythedev I checked out GitHub Search API documentation. There doesn't seem to be any query parameter for getting repos by spoken language. As for the image you mentioned, that is from the trending repos section. A get request on that url with the query parameters returns HTML  so I guess we will have to proceed with scraping. Let me know if there is any alternate way.
