### ISSUE TITLE
Textwrap problems for chinese characters

### ISSUE THREAD

**Issue by hedythedev** [hedythedev/starcli#46]
<img width="778" alt="starcli-chi" src="https://user-images.githubusercontent.com/50042066/87238335-e86c2880-c433-11ea-8b48-6d705e1e62b2.png">

English seems to be working fine, but looks like textwrap has some problems for Chinese description, and the code that causes it is here:
https://github.com/hedythedev/starcli/blob/503adecbe49db9e5f035983a1820d79a4f4a8f2f/starcli/layouts.py#L83-L90

[rich.text](https://rich.readthedocs.io/en/latest/reference/text.html) can help with Chinese characters wrapping

**Comment by willmcgugan** [comment]
Yeah, the Text class will handle that. The standard library doesn’t account for Asian character widths, or Emojis.

**Comment by hedythedev** [comment]
Got it, thanks!
