### ISSUE TITLE
Add 'last updated' option 

### ISSUE THREAD

**Issue by hedythedev** [hedythedev/starcli#49]
We should add a `--updated` or `--last-updated` to find repos that are updated within a specified time period, can be achieved using: https://docs.github.com/en/github/searching-for-information-on-github/searching-for-repositories#search-by-when-a-repository-was-created-or-last-updated 

Remember to update the readme if possible to document the new option

**Comment by ylchao** [comment]
Hello, can I work on this enhancement? Seems like a very useful feature.

**Comment by hedythedev** [comment]
Sure @ylchao
