### ISSUE TITLE
Feature: Search by User

### ISSUE THREAD

**Issue by arcanearronax** [hedythedev/starcli#57]
**Description**

Create functionality to allow starcli to browse repos by Github user. This would display repos owned by the provided username.

**Why is it necessary? (or how would it make it better)**

This would allow the client to perform a more targeted search of repos. The client already displays the usernames for the owner of repos found. This would allow the client to further explore repos owned by an identified user, effectively adding a layer of depth to the existing breadth.

**how do you think should it be implemented? (If possible)**

A user would be able to pass a flag, such as "-U" or "--user" ("-u" is already used) to identify the user they want to find more repos for. When this flag is passed the API request would query the API for only the username, unless additional flags are provided. When a search by user is performed the same type of data about the repos will be displayed in the terminal, no change to the layout will occur.

**Anything you would like to include**

If this is acceptable, I can take on implementing this functionality.

**Comment by hedythedev** [comment]
@Saif807380 is working on implementing the search from the github.com/trending page, which is in [here](https://github.com/hedythedev/starcli/blob/23d20245b11e26dfbe3c2bd47087c589e1c8524e/starcli/search.py#L124) I think extending that function would be fine

**Comment by Saif807380** [comment]
Yes, I'll finish up with #44 which can then be extended.

**Comment by hedythedev** [comment]
I think how this can be implemented is that when someone use `--user` and provide a user name, it will search the trending repositories based on that username, but if a username is not provided, we can use github trending page to find popular users

**Comment by arcanearronax** [comment]
It looks like Saif807380 finished working on issue #44 (as this issue has been closed). If I am correct, will it be fine to begin working on this?

**Comment by hedythedev** [comment]
Yes @arcanearronax

**Comment by hedythedev** [comment]
It seems finding and displaying trending users is more complex than I thought, guess I'll open a separate issue to keep track of that
