### ISSUE TITLE
Bug: TypeError: cli() got an unexpected keyword argument 'topic'

### ISSUE THREAD

**Issue by jSadoski** [hedythedev/starcli#72]
**Description**

Running starcli returned this error, as `--topics` was renamed but not changed in the cli() parameters.

**Python version**

```bash
$ python --version
Python 3.7.0
```

**your operating system (and terminal type of needed)**

```bash
$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.15.5
BuildVersion:   19F101
$ bash --version
GNU bash, version 5.0.18(1)-release (x86_64-apple-darwin19.5.0)
```

**starcli version**

57ae9cd

**any suggestions to the cause of the problem? (if possible)**

Rename/refactor `cli(.. topics, ...)` --> `cli(.. topic, ...)`

**Comment by hedythedev** [comment]
Thanks, I forgot to change that when I renamed the option. It seems CLI tests are really important 😅
