### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by jSadoski** [hedythedev/starcli#74]
**Description**

I'm getting this error:

```python
Exception has occurred: TypeError
style() got an unexpected keyword argument 'end'
```
when hitting this line:

https://github.com/hedythedev/starcli/blob/57ae9cdce0b3bddd27a1bbdb3b665a641c627fc7/starcli/__main__.py#L134

**Python version**

```bash
$ python --version
Python 3.7.0
```

**your operating system (and terminal type of needed)**

```bash
$ pip freeze | grep click
click==7.1.2

$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.15.5
BuildVersion:   19F101

$ bash --version
GNU bash, version 5.0.18(1)-release (x86_64-apple-darwin19.5.0)
```

**starcli version**

57ae9cd

**any suggestions to the cause of the problem? (if possible)**
What is this line for? I can't find any documentation for it in [`click.secho`](https://click.palletsprojects.com/en/7.x/api/?highlight=secho#click.secho) or [`click.style`](https://click.palletsprojects.com/en/7.x/api/?highlight=secho#click.style).

**Comment by hedythedev** [comment]
It seems we have to use `nl=True` instead, because it had initially been `print`, then I changed it to `secho`
> nl – if set to True (the default) a newline is printed afterwards.

But according to that we could just remove it completely.
