### ISSUE TITLE
Better debug logging - Use rich.logging

### ISSUE THREAD

**Issue by hedythedev** [hedythedev/starcli#81]
**Description**

Currently we are using the python print function to print debug info when users use `--debug`, it would be better practice to use a logger [(rich.logging)](https://rich.readthedocs.io/en/latest/logging.html) to log debug information, as well as requests debug info

**how do you think should it be implemented? (If possible)**

* Update [`debug_requests_on` in search.py](https://github.com/hedythedev/starcli/blob/bef20979330b97f987d993cc64050369c4968745/starcli/search.py#L31-L41) to use rich logger
* Update debug print lines in [search.py](https://github.com/hedythedev/starcli/blob/main/starcli/search.py) To use the logger
* Update [`test_cli_debug` In CLI tests](https://github.com/hedythedev/starcli/blob/main/tests/test_cli.py) if needed

**Comment by ineelshah** [comment]
What's the status of this?

**Comment by hedythedev** [comment]
feel free to pick it if you like :smile:

**Comment by ineelshah** [comment]
I am going to try helping with it.

**Comment by ineelshah** [comment]
Hi @hedythedev .
Check it out. Hopefully solves it.
Thanks for letting me solve it.
